"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["textinator.py"]
DATA_FILES = ["icon.png"]
OPTIONS = {
    "iconfile": "icon.icns",
    "plist": {
        "LSUIElement": True,
        "NSDesktopFolderUsageDescription": "Textinator needs access to your Desktop folder to detect new screenshots. "
        "If you have changed the default location for screenshots, "
        "you will also need to grant Textinator full disk access in "
        "System Preferences > Security & Privacy > Privacy > Full Disk Access.",
        "NSAppleEventsUsageDescription": "Textinator needs permission to send AppleScript events to add itself to Login Items.",
    },
}

setup(
    app=APP,
    data_files=DATA_FILES,
    name="Textinator",
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
